baseurl = "https://blog.davidhaberthuer.ch"
DefaultContentLanguage = "en"
title = "blog.davidhaberthuer.ch"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"


[Params]
  description = "General geekery. Powered by Hugo"
  subtitle = "Used to be somewhere else..."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "2. January, 2006"
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  # Commit SHA in the footer (https://github.com/halogenica/beautifulhugo)
  commit = "https://github.com/habi/blog/tree/"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "David Haberthür"
  website = "blog.davidhaberthuer.ch"
  email = "email@davidhaberthuer.ch"
  github = "habi"
  twitter = "habi"
  reddit = "freischwimmer"
  linkedin = "haberthuer"
  stackoverflow = "users/323100/habi"
  youtube = "user/habi" # or channel/channelname
  soundcloud = "davidhaberthuer"
  spotify = "username"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
