title = "This used to be habi.gna.ch"
baseURL = "https://blog.davidhaberthuer.ch"
languageCode = "en-us"
publishDir = "public"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
enableRobotsTXT = true
recent_posts_number = 15
rssLimit = 15

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "General geekery"
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-" 
  background_color_class = "bg-green"
  
[permalinks]
  posts = "/:year/:month/:day/:slug/"


[[params.ananke_socials]]
name = "GitHub"
url = "http://github.com/habi" 
name = "Mastodon"
url = "https://mastodon.social/@habi"
name = "Linkedin"
url = "https://www.linkedin.com/in/haberthuer/"
nanme = "Youtube"
url = "http://youtube.com/habi"
