baseURL = "https://blog.davidhaberthuer.ch"
languageCode = "en-us"
title = "This used to be habi.gna.ch"
theme = "ananke"
[permalinks]
  posts = "/:year/:month/:day/:slug/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/habi"
  instagram = ""
  youtube = "http://youtube.com/habi"
  github = "http://github.com/habi"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/haberthuer/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-green"
  recent_posts_number = 10
