baseURL = "https://blog.davidhaberthuer.ch"
languageCode = "en-us"
publishDir = "public"
theme = "ananke"
title = "This used to be habi.gna.ch"
[params]
	background_color_class = "bg-green"
	description = "The last theme you'll ever need. Maybe."
	facebook = ""
	favicon = ""
	github = "http://github.com/habi"
	gitlab = ""
	instagram = ""
	linkedin = "https://www.linkedin.com/in/haberthuer/"
	recent_posts_number = 10
	twitter = "https://twitter.com/habi"
	youtube = "http://youtube.com/habi"
[permalinks]
	posts = "/:year/:month/:day/:slug/"
[sitemap]
	changefreq = "monthly"
	filename = "sitemap.xml"
	priority = 0.50000000000000000
